-- Deprecated placeholder migration.
-- The debug_storage_policies helper is now defined in 0003_debug_storage_policies.sql.
-- This file is kept to preserve migration ordering but intentionally does nothing.
